### ISSUE TITLE
Устанавливать в качестве веса ребра по умолчанию расстояние между соединяемыми вершинами

### ISSUE THREAD

**Issue by Fikafusik** [Fikafusik/AStarVisualizer#27]
В классе `Point` реализовать метод `distanceTo(Point point)`. При создании ребра выставлять вес через этот метод. Желательно развить идею: при перемещении вершины, все инцидентные ей рёбра должны в соответствии с новым расстоянием изменять веса.

**Comment by Anastasiyalp** [comment]
Done
