### ISSUE TITLE
Избавиться от анонимных слушателей

### ISSUE THREAD

**Issue by Fikafusik** [Fikafusik/AStarVisualizer#28]
В целях сокращения объёма кода в конструкторах классов необходимо избавить от анонимных слушателей в классах `AStarInterface` и `AStarVisulizer`. Для этого внутри соответствующих классов определяете в явном виде классы-слушателей: `public class NextButtonListener implements ActionListener { ... }`. Соответственно при добавлении обработчика должно быть написано просто: `nextButton.addActionListener(new NextButtonListener())`.

**Comment by Anastasiyalp** [comment]
Сделано настолько насколько написан код
