### ISSUE TITLE
Исправить баг с масштабированием графа

### ISSUE THREAD

**Issue by Fikafusik** [Fikafusik/AStarVisualizer#6]
После отдаления и повторного приближении графа, вершины появляются в стороне от курсора. Расстояние от курсора до вершины как-то зависит от расстояния от левого верхнего угла до курсора.

**Comment by Anastasiyalp** [comment]
Показалось нецелесообразным решать эту проблему сейчас. Удалила зум. Если будет время на эту фичу, то добавим ее в конце
